// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230623202159_VehicleAddition")]
    partial class VehicleAddition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApi.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)")
                        .HasColumnName("message_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("text");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            Text = "This is a test message."
                        },
                        new
                        {
                            MessageId = 2,
                            Text = "I really like working in C#!"
                        },
                        new
                        {
                            MessageId = 3,
                            Text = "I really like working in Javascript!"
                        },
                        new
                        {
                            MessageId = 4,
                            Text = "Anyone else playing Diablo IV?"
                        },
                        new
                        {
                            MessageId = 5,
                            Text = "The meaning of life isn't about the what is seen through the eye of the beholder, but what the brain behind it percieves."
                        });
                });

            modelBuilder.Entity("WebApi.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("colour");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("model");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int(4)")
                        .HasColumnName("model_year");

                    b.Property<decimal>("PurchaseAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("purchase_amount");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("purchase_date");

                    b.Property<decimal?>("SaleAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("sale_amount");

                    b.Property<DateTime?>("SaleDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sale_date");

                    b.Property<string>("TrimLevel")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("trim_level");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("varchar(18)")
                        .HasColumnName("vin");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            Colour = "Blue",
                            Manufacturer = "TestManufacturer",
                            Model = "TestModel",
                            ModelYear = 2003,
                            PurchaseAmount = 1000m,
                            PurchaseDate = new DateTime(2023, 6, 23, 14, 21, 59, 571, DateTimeKind.Local).AddTicks(9508),
                            TrimLevel = "TestTrim",
                            VIN = "11111111111111111"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
