// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Data;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230611030420_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApi.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)")
                        .HasColumnName("message_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("text");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            Text = "This is a test message."
                        },
                        new
                        {
                            MessageId = 2,
                            Text = "I really like working in C#!"
                        },
                        new
                        {
                            MessageId = 3,
                            Text = "I really like working in Javascript!"
                        },
                        new
                        {
                            MessageId = 4,
                            Text = "Anyone else playing Diablo IV?"
                        },
                        new
                        {
                            MessageId = 5,
                            Text = "The meaning of life isn't about the what is seen through the eye of the beholder, but what the brain behind it percieves."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
